spring:
  rabbitmq:
    addresses: 39.107.234.188
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual #设置消息手工签收
        concurrency: 5
        max-concurrency: 10
