spring:
  rabbitmq:
    addresses: 39.107.234.188
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
     mandatory: true # 防止消息不可达自动删除消息
